[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsa = "0.6.0"
rand = "0.8.5"
base64 = "0.13.0"
chrono = "0.4"
yaml-rust = "0.4.5"
